question_data = [
    {"type": "boolean", "difficulty": "medium", "category": "Animals",
     "question": "An octopus can fit through any hole larger than its beak.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography",
     "question": "Miami is Florida's largest city.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "Android versions are named in alphabetical order.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "History",
     "question": "Vikings were the first Europeans to discover North America.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "Slovakia is a member of European Union-", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "Mythology",
     "question": "Janus was the Roman god of doorways and passageways.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "In Portal, the Companion Cube's ARE sentient.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "History",
     "question": "The Spitfire originated from a racing plane.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Vehicles",
     "question": "The full English name of the car manufacturer BMW is Bavarian Motor Works",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
     "question": "\"Friday\" the single by Rebecca Black, was released in February 10th, 2011.",
     "correct_answer": "True", "incorrect_answers": ["False"]}
]
